---
name: Terraform Quality Assurance
description: 'Pipeline that ensures the quality of Terraform code using pre-commit'
permissions:
  contents: write
runs:
  using: "composite"
  steps:
    - name: 'install'
      id: 'install'
      run: |
        sudo apt install python3-pip
        pip install pre-commit
        pip install detect-secrets
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      shell: bash
    - name: 'pre-commit'
      id: 'pre-commit'
      run: |
        # Copy the pre-commit-terraform-qa.yaml file in the repository where the action is defined to the repository where the action is executed
        cp ${GITHUB_ACTION_PATH}/pre-commit-terraform-qa.yaml .pre-commit-config.yaml
        detect-secrets scan > .secrets.baseline
        pre-commit install
        pre-commit run --all-files
      shell: bash
    - name: 'auto-linting'
      id: 'auto-linting'
      uses: EndBug/add-and-commit@v9.1.3
      if: always()
      with:
        add: '-u *' # this ignores files created at pipeline time and files under .github
        commit: '--no-verify'
        message: "fix: auto linting"
        default_author: github_actor