---
name: Terraform Quality Assurance
description: 'Pipeline that ensures the quality of Terraform code using pre-commit'
permissions:
  contents: write
runs:
  using: "composite"
  steps:
    - name: 'install-dependencies'
      id: 'install-dependencies'
      shell: bash
      run: |
        sudo apt install python3-pip
        pip install pre-commit
        pip install detect-secrets
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        curl -sSLo /tmp/terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
        tar -xzf /tmp/terraform-docs.tar.gz -C /tmp
        chmod +x /tmp/terraform-docs
        mv /tmp/terraform-docs /usr/local/bin/terraform-docs
    - name: 'apply-configuration'
      id: 'apply-configuration'
      shell: bash
      run: |
        # Copy the pre-commit configuration files in the repository where the action is defined to the repository where the action is executed
        cp ${GITHUB_ACTION_PATH}/pre-commit-terraform-qa.yaml pre-commit-terraform-qa.yaml
        cp ${GITHUB_ACTION_PATH}/pre-commit-auto-linting.yaml pre-commit-auto-linting.yaml
        # Copy the terraform-docs-terraform-qa.yml file in the repository where the action is defined to the repository where the action is executed
        cp ${GITHUB_ACTION_PATH}/terraform-docs-terraform-qa.yml .terraform-docs.yml
        # Copy the tflint.hcl file in the repository where the action is defined to the repository where the action is executed
        cp ${GITHUB_ACTION_PATH}/.tflint.hcl .tflint.hcl
        tflint --init
        detect-secrets scan > .secrets.baseline
    - name: 'pre-commit-qa'
      id: 'pre-commit-qa'
      shell: bash
      run: |
        pre-commit install --config pre-commit-terraform-qa.yaml
        pre-commit run --all-files
    - name: 'pre-commit-lint'
      continue-on-error: true
      id: 'pre-commit-lint'
      shell: bash
      run: |
        pre-commit install --config pre-commit-auto-linting.yaml
        pre-commit run --all-files
    - name: 'auto-linting'
      id: 'auto-linting'
      uses: EndBug/add-and-commit@v9.1.3
      if: always()
      with:
        add: '-u' # this ignores files created at pipeline time
        commit: '--no-verify'
        message: "fix: auto linting"
        default_author: github_actor