---
name: Terraform Quality Assurance
description: 'Pipeline that ensures the quality of Terraform code using pre-commit'
runs:
  using: "composite"
  steps:
    - name: 'install'
      id: 'install'
      run: |
        sudo apt install python3-pip git
        pip install pre-commit
        pip install detect-secrets
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      shell: bash
    - name: 'pre-commit'
      id: 'pre-commit'
      run: |
        # Copy the pre-commit-terraform-qa.yaml file in the repository where the action is defined to the repository where the action is executed
        cp ${GITHUB_ACTION_PATH}/pre-commit-terraform-qa.yaml .pre-commit-config.yaml
        detect-secrets scan > .secrets.baseline
        pre-commit install
        pre-commit run --all-files
      shell: bash
    - name: 'auto terraform fmt'
      id: 'terraform-fmt'
      run: |
        git status
        git commit -am "fix: terraform fmt"
        git push
      shell: bash